version: "3.1"
services:
  db:
    container_name: mysql_wordpress_poison
    build: 
      context: .
      dockerfile: Dockerfile_db
    ports: 
      - "9001:3306"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - poison_db_data:/var/lib/mysql
    mem_limit: 512m
  wordpress:
    container_name: wordpress_poison
    build: 
      context: .
      dockerfile: Dockerfile_wordpress
    #volumes:
    #  - ./wordpress_files:/var/www/html/
    ports: 
      - "8004:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - poison_wordpress_data:/var/www/html
  phpmyadmin:
    container_name: phpmyadmin_wordpress_poison
    image: phpmyadmin/phpmyadmin
    links: 
      - db:db
    ports:
      - 8005:80
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
volumes:
  poison_db_data:
  poison_wordpress_data: